#!/bin/bash
if [ -f nohup.out ]; then rm nohup.out; fi
SCRIPT_DIR="$PWD"
cd $SCRIPT_DIR
# grab the port number
port=4097
if [ "$1" != "" ]; then port=$1; fi

# set up
cd ./reports
if [ -f shutdown.txt ]; then rm -f shutdown.txt; fi

cd ../area

# allow cores
ulimit -c unlimited
# stack limit
ulimit -s 100000

renice 0 -p $$

# loop indefinately
while :
do
  # find a logfile

  index=1000
  while :
  do
    logfile=../log/$index.log
    if [ ! -e $logfile ]; then break; fi
    let index=$index+1
  done

  # run the mud
  ../src/ack $port >$logfile 2>&1

  # shutdown?

cd ../reports

  if [ -e shutdown.txt ]; then
    echo "startup: shutting down" >>$logfile
    rm -f shutdown.txt
    exit 1
  fi

cd ../area
  
  if [ -f core ]; then uuencode core core | mail "$(whoami)" -s "COREDUMP"; fi
  if [ -f core ]; then rm -rf core; fi
  # sleep, so if we fail on boot we don't get massive looping
  sleep 5
done
